export const sidebarSections = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "🏠",
    path: "dashboard",
  },
  {
    id: "content",
    label: "CONTENT",
    type: "heading",
  },
  {
    id: "problems",
    label: "Problems",
    icon: "📚",
    children: [
      { id: "problems-all", label: "All Problems", path: "problems/all" },
      { id: "problems-add", label: "Add Problem", path: "problems/add" },
      { id: "problems-draft", label: "Draft Problems", path: "problems/draft" },
      { id: "problems-tags", label: "Problem Tags", path: "problems/tags" },
    ],
  },
  {
    id: "practice",
    label: "Practice",
    icon: "🎯",
    children: [
      { id: "practice-languages", label: "Languages", path: "practice/languages" },
      { id: "practice-modules", label: "Modules", path: "practice/modules" },
      {
        id: "practice-questions",
        label: "Practice Questions",
        path: "practice/questions",
      },
    ],
  },
  {
    id: "contests",
    label: "Contests",
    icon: "🏆",
    children: [
      { id: "contests-all", label: "All Contests", path: "contests" },
      { id: "contests-create", label: "Create Contest", path: "contests/create" },
      { id: "contests-leaderboard", label: "Leaderboard", path: "contests/leaderboard" },
    ],
  },
  {
    id: "users-heading",
    label: "USERS",
    type: "heading",
  },
  {
    id: "students",
    label: "Students",
    icon: "👤",
    path: "users/students",
  },
  {
    id: "mentors",
    label: "Mentors",
    icon: "👨‍🏫",
    path: "users/mentors",
    badge: "Soon",
  },
  {
    id: "admins",
    label: "Admins",
    icon: "🛡",
    path: "users/admins",
    badge: "Soon",
  },
  {
    id: "monitoring-heading",
    label: "MONITORING",
    type: "heading",
  },
  {
    id: "submissions",
    label: "Submissions",
    icon: "📄",
    path: "monitoring/submissions",
    badge: "Soon",
  },
  {
    id: "analytics",
    label: "Analytics",
    icon: "📈",
    path: "monitoring/analytics",
    badge: "Soon",
  },
  {
    id: "reports",
    label: "Reports",
    icon: "⚠",
    path: "monitoring/reports",
    badge: "Soon",
  },
  {
    id: "website-heading",
    label: "WEBSITE",
    type: "heading",
  },
  {
    id: "questions",
    label: "Question Bank",
    icon: "❓",
    path: "questions",
  },
  {
    id: "add-question",
    label: "Add Question",
    icon: "➕",
    path: "questions/add",
  },
  {
    id: "settings-heading",
    label: "SETTINGS",
    type: "heading",
  },
  {
    id: "settings",
    label: "General",
    icon: "⚙",
    path: "settings",
    badge: "Soon",
  },
];

export const breadcrumbLabels = {
  dashboard: "Dashboard",
  "problems/all": "All Problems",
  "problems/add": "Add Problem",
  "problems/draft": "Draft Problems",
  "problems/tags": "Problem Tags",
  "practice/languages": "Languages",
  "practice/modules": "Modules",
  "practice/questions": "Practice Questions",
  contests: "Contest Settings",
  "contests/create": "Create Contest",
  "contests/leaderboard": "Leaderboard",
  "users/students": "Students",
  questions: "Question Bank",
  "questions/add": "Add Question",
};
